const images = {
  splashLogo: require("../images/png/splash-logo.png"),
  splashBackgroud: require("../images/png/Splash-bg.png"),
  photo1: require("../images/png/photo1.jpeg"),
  photo: require("../images/png/photo.jpeg"),
  play: require("../images/png/play.png"),
  close: require("../images/png/popup-close.png"),
  check: require("../images/png/checked.png"),
  unCheck: require("../images/png/unchecked.png"),
  camera: require("../images/png/camera.png"),
  gallery: require("../images/png/gallery.png"),
  loadingImage: require("../images/png/Preloader.gif"),
  blankProfile: require("../images/png/blankProfile.png"),
  heartImage: require("../images/png/heart.png"),
  downarrow: require("../images/png/downarrow.png"),
  share: require("../images/png/share.png"),
  football_status: require("../images/png/football_status.png"),
  bluetooth: require("../images/png/bluetooth.png"),
  frnd_req_rejected: require("../images/png/frnd_req_rejected.png"),
  chat: require("../images/png/chat.png"),
  debate_lost: require("../images/png/debate_lost.png"),
  notification: require("../images/png/notification.png"),
  del: require("../images/png/delete_icon.png"),
};

export default images;
